FROM ubuntu:latest
RUN apt update && apt install  openssh-server sudo python3 less -y
RUN useradd -rm -d /home/ansible -s /bin/bash -g root -G sudo -u 1000 ansible
RUN mkdir -p /home/ansible/.ssh && \
	chown -R ansible /home/ansible/.ssh
RUN  echo 'ansible:ansible' | chpasswd
RUN service ssh start
CMD ["/usr/sbin/sshd","-D"]

