- name: Set up users
  hosts: database
  roles:
    - db-users
    
- name: Set up databases
  hosts: database
  tasks:
    - name: Install MySQL
      become: true
      ansible.builtin.apt:
        name: mysql-server
        state: present

    - name: Start MySQL
      become: true
      ansible.builtin.shell:
        cmd: "/etc/init.d/mysql restart"
        
- name: Set up backend
  hosts: backend
  tasks:
    - name: Install java
      become: true
      ansible.builtin.apt:
        name: default-jre
        state: present